/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Admin;

import Models.*;
import Controller.*;
import java.util.List;


/**
 *
 * @author gerar
 */
public class AdminSquads extends javax.swing.JPanel {
    CuadrillaDAO squadDAO = new CuadrillaDAO();

    /**
     * Creates new form AdminUsers
     */
    public AdminSquads() {
        initComponents();
        updateSquads(); //Actualizar combo box de cuadrillas cada vez que entra al Panel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();
        squadLabel = new javax.swing.JLabel();
        squadComboBox = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        title1.setFont(new java.awt.Font("Bahnschrift", 1, 28)); // NOI18N
        title1.setText("ADMINISTRAR CUADRILLAS");

        nameLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        nameLabel.setText("Nombre de la Cuadrilla:");
        nameLabel.setToolTipText("");

        nameTextField.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        nameTextField.setToolTipText("Ingresa el nombre de la cuadrilla a agregar");

        insertButton.setBackground(new java.awt.Color(128, 237, 153));
        insertButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        insertButton.setForeground(new java.awt.Color(0, 0, 0));
        insertButton.setText("AGREGAR");
        insertButton.setToolTipText("Agregar un nueva cuadrilla");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        squadLabel.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        squadLabel.setText("Cuadrilla");

        squadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoge la cuadrilla:" }));
        squadComboBox.setToolTipText("Escoger una cuadrilla para actualizar o eliminar");

        updateButton.setBackground(new java.awt.Color(20, 145, 155));
        updateButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(0, 0, 0));
        updateButton.setText("ACTUALIZAR");
        updateButton.setToolTipText("Actualizar una cuadrilla");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        deleteButton.setText("ELIMINAR");
        deleteButton.setToolTipText("Elimina una cuadrilla");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(33, 58, 87));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel2.setText("SISTEMA DE LIMPIEZA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(402, 402, 402))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(title1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(45, 45, 45)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(insertButton)
                        .addGap(549, 549, 549))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(squadLabel)
                        .addGap(44, 44, 44)
                        .addComponent(squadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(397, 397, 397))))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(updateButton)
                .addGap(320, 320, 320)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(title1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(insertButton)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(squadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(squadLabel))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Evento del botón AGREGAR, aquí se manejarán las inserciones.
    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        if (nameTextField.getText().trim().isEmpty()){
        
        // Mostrar mensaje de error si faltan campos
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, rellene todos los campos antes de continuar.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    } else {
        String nombreCuadrilla = nameTextField.getText().trim();

        // Crear una nueva cuadrilla
        Cuadrilla nuevaCuadrilla = new Cuadrilla();
        nuevaCuadrilla.setNombre(nombreCuadrilla);

        // Llamar al DAO para insertar la cuadrilla
        try {
            squadDAO.insertarCuadrilla(nuevaCuadrilla);
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cuadrilla registrada exitosamente.", 
                "Éxito", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Actualizar ComboBoxes después de insertar
            updateSquads();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al registrar la cuadrilla: " + ex.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // Actualizar los ComboBoxes después de insertar
    }
        updateSquads(); //Después de insertar debe actualizar el combo box
    }//GEN-LAST:event_insertButtonActionPerformed

    // Evento del botón ACTUALIZAR, aquí se manejarán las actualizaciones.
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if (nameTextField.getText().trim().isEmpty()) {
        // Validar que el campo de nombre no esté vacío
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, ingrese el nuevo nombre de la cuadrilla.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    } else {
        // Obtener el texto seleccionado en el combo box
        String cuadrillaSeleccionada = (String) squadComboBox.getSelectedItem();
        System.out.println("Texto seleccionado: " + cuadrillaSeleccionada); // Debug

        try {
            // Extraer el ID de la cuadrilla del texto (formato: "ID: <id> Nombre: <nombre>")
            int idCuadrilla = Integer.parseInt(cuadrillaSeleccionada.split(":")[1].trim().split(" ")[0]);
            System.out.println("ID extraído: " + idCuadrilla); // Debug

            // Capturar el nuevo nombre de la cuadrilla
            String nuevoNombre = nameTextField.getText().trim();

            // Confirmar la actualización con el usuario
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea actualizar esta cuadrilla?\n" + 
                "Nuevo nombre: " + nuevoNombre, 
                "Confirmar actualización", 
                javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                // Crear objeto Cuadrilla con el nuevo nombre
                Cuadrilla cuadrillaActualizada = new Cuadrilla();
                cuadrillaActualizada.setNombre(nuevoNombre);

                // Llamar al DAO para actualizar la cuadrilla
                boolean actualizado = squadDAO.actualizarCuadrilla(cuadrillaActualizada, idCuadrilla);
                if (actualizado) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Cuadrilla actualizada exitosamente.", 
                        "Éxito", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Actualizar ComboBoxes después de actualizar
                    updateSquads();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "No se pudo actualizar la cuadrilla. Verifique los datos.", 
                        "Error", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al actualizar la cuadrilla: " + ex.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
        // IMPORTANTE: Tomar ID de cuadrilla del ComboBox
         updateSquads(); //Después de actualizar debe actualizar el combo box
    }//GEN-LAST:event_updateButtonActionPerformed

    // Evento del botón ELIMINAR, aquí se manejarán los elementos eliminados.
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Obtener el texto seleccionado en el combo box
        String cuadrillaSeleccionada = (String) squadComboBox.getSelectedItem();
        System.out.println("Texto seleccionado: " + cuadrillaSeleccionada); // Debug

        try {
            // Extraer el ID de la cuadrilla del texto (formato: "ID: <id> Nombre: <nombre>")
            int idCuadrilla = Integer.parseInt(cuadrillaSeleccionada.split(":")[1].trim().split(" ")[0]);
            System.out.println("ID extraído: " + idCuadrilla); // Debug

            // Confirmar eliminación con el usuario
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar esta cuadrilla?\n" + cuadrillaSeleccionada, 
                "Confirmar eliminación", 
                javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                // Llamar al DAO para eliminar la cuadrilla
                squadDAO.eliminarCuadrilla(idCuadrilla);
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Cuadrilla eliminada exitosamente.", 
                    "Éxito", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // Actualizar ComboBoxes después de eliminar
                updateSquads();
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al eliminar la cuadrilla: " + ex.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // IMPORTANTE: Tomar ID de cuadrilla del ComboBox
         updateSquads(); //Después de eliminar debe actualizar el combo box
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Actualizar combo box de usuarios
    private void updateSquads(){
        List<Cuadrilla> squads = squadDAO.obtenerCuadrillas();
        squadComboBox.removeAllItems();
        
        for(Cuadrilla squad: squads){
            squadComboBox.addItem("ID: " + squad.getId_cuadrilla() + " Nombre de Cuadrilla: " + squad.getNombre());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> squadComboBox;
    private javax.swing.JLabel squadLabel;
    private javax.swing.JLabel title1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
