/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Admin;

import Models.ActividadLimpieza;
import Controller.ActividadLimpiezaDAO;
import java.util.List;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.io.File;

/**
 *
 * @author gerar
 */
public class ListActivities extends javax.swing.JPanel {

    ActividadLimpiezaDAO activityD = new ActividadLimpiezaDAO();

    /**
     * Creates new form ListUsers
     */
    public ListActivities() {
        initComponents();
        showActivities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listUsersTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activityTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 777));
        setRequestFocusEnabled(false);

        listUsersTitle.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        listUsersTitle.setText("CATÁLOGO DE ACTIVIDADES");

        activityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID de Actividad", "Descripción", "Fecha", "Retroalimentación", "Evidencia", "Cuadrilla", "Completado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(activityTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(listUsersTitle)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(listUsersTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showActivities() {
        List<ActividadLimpieza> actividad = activityD.obtenerTodasLasActividades();
        DefaultTableModel model = (DefaultTableModel) activityTable.getModel();
        model.setRowCount(0);

        for (ActividadLimpieza act : actividad) {
            Object[] row = {
                act.getId_actividad(),
                act.getDescripcion(),
                act.getFecha(),
                act.getRetroalimentacion(),
                act.getImagenEvidencia(), // Ruta de la imagen
                act.getCuadrilla().getNombre(),
                act.isTerminado()
            };
            model.addRow(row);
        }

        // Configurar renderizador para la columna de imágenes
        activityTable.setRowHeight(80);
        configureTableRenderer();
    }

    public class ImageRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus,
                int row, int column) {
            JLabel label = new JLabel();
            label.setHorizontalAlignment(JLabel.CENTER); 
            label.setVerticalAlignment(JLabel.CENTER);
            if (value != null) {
                String imagePath = value.toString();
                File imageFile = new File(imagePath);

                // Verificar si la imagen existe como ruta absoluta o relativa
                if (!imageFile.exists()) {
                    imagePath = System.getProperty("user.dir") + "/" + imagePath;
                    imageFile = new File(imagePath);
                }

                if (imageFile.exists()) {
                    ImageIcon icon = new ImageIcon(imagePath);
                    // Escalar la imagen si es necesario
                    Image scaledImage = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
                    label.setIcon(new ImageIcon(scaledImage));
                } else {
                    label.setText("Imagen no encontrada");
                }
            }
            return label;
        }
    }

    private void configureTableRenderer() {
        activityTable.getColumnModel().getColumn(4).setCellRenderer(new ImageRenderer());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable activityTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listUsersTitle;
    // End of variables declaration//GEN-END:variables
}
